# ── Big scale: 8xH100 SXM (Flash Attention 3 / Hopper) ───────────────────────
# Usage: NPROC=8 LARGE_GPU=1 bash big_scale_script_hopper.sh
NPROC=${NPROC:-8}
LARGE_GPU=${LARGE_GPU:-1}
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PYTHON="${SCRIPT_DIR}/.venv/bin/python3"

# FA3 requires torch shared libs on LD_LIBRARY_PATH and hopper/ on PYTHONPATH
TORCH_LIB="${SCRIPT_DIR}/.venv/lib/python3.12/site-packages/torch/lib"
FA3_PATH="/home/ubuntu/flash-attention/hopper"
export LD_LIBRARY_PATH="${TORCH_LIB}${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
export PYTHONPATH="${FA3_PATH}${PYTHONPATH:+:$PYTHONPATH}"

if [ "$NPROC" -gt 1 ]; then
    LAUNCHER=("$PYTHON" -m torch.distributed.run --nproc_per_node="$NPROC" --standalone)
else
    LAUNCHER=("$PYTHON")
fi

# RUN_ID=big_scale_524288_sub_fix_xsa \
# SEED_ID=1337 \
# NUM_LAYERS=11 MODEL_DIM=512 NUM_HEADS=8 NUM_KV_HEADS=4 MLP_HIDDEN=1536 \
# MLP_INT6=0 \
# USE_SWIGLU=1 USE_BAYES_MLP=1 USE_POWER_MLP_SWIGLU=1 \
# NOPE_RATIO=0.25 NOPE_MODE=block \
# USE_ALIBI=0 \
# TRAIN_BATCH_TOKENS=524288 TRAIN_SEQ_LEN=2048 \
# ITERATIONS=20000 WARMDOWN_ITERS=3500 WARMUP_STEPS=20 LR_WARMUP_STEPS=20 \
# VAL_LOSS_EVERY=0 VAL_BATCH_SIZE=786432 \
# TRAIN_LOG_EVERY=250 \
# QUANT_AUTO_BUDGET_MB=16 MAX_WALLCLOCK_SECONDS=600 \
# LARGE_GPU="${LARGE_GPU}" \
# EMA_ENABLED=1 EMA_DECAY=0.995 \
# LN_SCALE=1 \
# BACKOUT_ENABLED=1 BACKOUT_LAMBDA_INIT=0.12 BACKOUT_LAYER=-1 \
# USE_ADAMUON=1 ADAMUON_BETA2=0.92 \
# USE_ATTNRES=0 \
# ATTNRES_BLOCK_SIZE=4 \
# USE_BIGRAM=1 BIGRAM_BUCKETS=2048 BIGRAM_DIM=128 \
# USE_SHARED_VALUE_EMB=1 \
# TIE_EMBEDDINGS=1 LOGIT_SOFTCAP=30.0 \
# USE_LORA=1 LORA_RANK=16 \
# GRAD_CLIP_NORM=0.1 \
# FOCAL_GAMMA=0.6 \
# TTT_ENABLED=0 \
# TTT_EPOCHS=10 \
# TTT_LR=1e-4 \
# TTT_BATCH_SEQS=32 \
# TTT_FREEZE_BLOCKS=0 \
# LATE_QAT=1 \
# LATE_QAT_THRESHOLD=0.10 \
# LR_WARMUP_STEPS=0 \
# SWA_ENABLED=1 \
# SWA_EVERY=50 \
# USE_XSA=1 \
# XSA_LAYERS=4 \
# EVAL_STRIDE=1024 \
# VE_ENABLED=1 VE_DIM=128 VE_LAYERS=9,10 \
# "${LAUNCHER[@]}" train_gpt_smear_attn_hopper.py


RUN_ID=power_swiglu_double \
SEED_ID=1337 \
NUM_LAYERS=11 MODEL_DIM=512 NUM_HEADS=8 NUM_KV_HEADS=4 MLP_HIDDEN=1536 \
MLP_INT6=1 \
USE_SWIGLU=1 USE_BAYES_MLP=0 USE_POWER_MLP_SWIGLU=1 \
NOPE_RATIO=0 \
USE_ALIBI=0 \
TRAIN_BATCH_TOKENS=524288 TRAIN_SEQ_LEN=2048 \
ITERATIONS=200 WARMDOWN_ITERS=3000 WARMUP_STEPS=20 LR_WARMUP_STEPS=20 \
VAL_LOSS_EVERY=1000 VAL_BATCH_SIZE=524288 \
TRAIN_LOG_EVERY=50 \
QUANT_AUTO_BUDGET_MB=15.0 MAX_WALLCLOCK_SECONDS=600 \
EMA_ENABLED=0 EMA_DECAY=0.999 \
LN_SCALE=1 \
BACKOUT_ENABLED=1 BACKOUT_LAMBDA_INIT=0.24 BACKOUT_LAYER=-1 \
USE_ADAMUON=1 ADAMUON_BETA2=0.92175 \
USE_ATTNRES=0 \
ATTNRES_BLOCK_SIZE=4 \
USE_BIGRAM=0 BIGRAM_BUCKETS=2048 \
BIGRAM_DIM=128 \
NOPE_MODE=block \
GRAD_CLIP_NORM=0.2 \
FOCAL_GAMMA=0.45 \
USE_SHARED_VALUE_EMB=0 \
USE_LORA=1 LORA_RANK=16 \
TTT_ENABLED=0 \
TTT_EPOCHS=10 \
TTT_LR=1e-4 \
TTT_BATCH_SEQS=32 \
TTT_FREEZE_BLOCKS=0 \
LATE_QAT=1 \
LATE_QAT_THRESHOLD=0.10 \
SWA_ENABLED=1 \
SWA_EVERY=10 \
VE_ENABLED=0 VE_DIM=128 VE_LAYERS=9,10 \
SKIP_SLIDING_EVAL=1 \
EVAL_STRIDE=1024 EVAL_BATCH_SEQS=128 \
"${LAUNCHER[@]}" train_gpt_smear_attn.py 


